version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  php56:
    build: /bctos/server/php56
    hostname: php56
    container_name: php56
    image: bctos-php:5.6-fpm-alpine
    restart: unless-stopped
    volumes:
      - /bctos/wwwroot:/bctos/wwwroot
      - /bctos/logs:/bctos/logs
      - /bctos/server/php56/php.ini:/usr/local/etc/php/php.ini
      - /bctos/server/php56/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    cap_add:
      - SYS_PTRACE