version: "3.1"
networks:
   default:
      name: bctos

services: 
   panel:
#      build: .
      hostname: panel
      container_name: panel
      image: registry.cn-hangzhou.aliyuncs.com/wxm201411/panel:latest
      restart: always
      ports: 
         - 667:3306
         - 666:80
         - 2100:2100
         - 2120:2120
         - 2121:2121
      volumes:
         - /bctos/server/panel/mysql-data:/var/lib/mysql
         - /bctos/server/panel/nginx.conf:/etc/nginx/nginx.conf
         - /bctos/server/panel/conf.d/default.conf:/etc/nginx/conf.d/default.conf
         - /bctos/server/panel/php-fpm.conf:/etc/php7/php-fpm.conf
         - /bctos/server/panel/php.ini:/etc/php7/php.ini
         - /bctos/server/panel/my.cnf:/etc/my.cnf
         - /bctos:/bctos
         - /:/myos
      cap_add:
         - SYS_PTRACE