version: "3.1"
networks: 
   default: 

services: 
   mysql: 
      build: 
         context: .
         dockerfile: mysql-dockerfile
      hostname: mysql
      container_name: mysql
      ports: 
         - 3307:3306
      volumes:
         - ./mysql-data:/var/lib/mysql
      environment: 
         MYSQL_ROOT_PASSWORD: 123456

   php: 
      build: 
         context: .
         dockerfile: php-dockerfile
      hostname: php
      container_name: php
      depends_on:
         - mysql
      ports: 
         - 9001:9000
      volumes:
         - ./wwwroot:/var/www/html
   msg: 
      build: 
         context: php
         dockerfile: msg-dockerfile
      hostname: msg
      container_name: msg
      ports: 
         - 2120:2120
         - 2121:2121
         - 2123:2123
      volumes:
         - ./wwwroot:/var/www/html
   socket: 
      build: 
         context: php
         dockerfile: socket-dockerfile
      hostname: socket
      container_name: socket
      ports: 
         - 2100:2100
      volumes:
         - ./wwwroot:/var/www/html

   nginx: 
      image: nginx
      hostname: nginx
      container_name: nginx
      depends_on:
         - php
      ports: 
         - 81:80
      volumes:
         - ./conf.d:/etc/nginx/conf.d
         - ./wwwroot:/var/www/html
      links: 
         - php