version: "3.8"
networks:
  default:
    external:
      name: bctos
services:
  mysql-mariadb101:
    hostname: mysql-mariadb101
    container_name: mysql-mariadb101
    image: mariadb:10.1
    restart: unless-stopped
    ports:
      - 3311:3306
    volumes:
      - /bctos/server/mysql-mariadb101/mysql-data:/var/lib/mysql
      - /bctos/server/mysql-mariadb101/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: bctos_panel