version: "3.1"
networks:
  default:
    external:
      name: bctos

services:
  memcached16:
    hostname: memcached16
    container_name: memcached16
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/memcached:1.6-alpine
    restart: unless-stopped