version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  mysql80:
    hostname: mysql80
    container_name: mysql80
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3380:3306
    volumes:
      - /bctos/server/mysql80/mysql-data:/var/lib/mysql
      - /bctos/server/mysql80/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: bctos_panel