version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  php74:
#    build: /bctos/server/php74
    hostname: php74
    container_name: php74
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/php:7.4
    restart: unless-stopped
    volumes:
      - /bctos/wwwroot:/bctos/wwwroot
      - /bctos/logs:/bctos/logs
      - /bctos/server/php74/php.ini:/usr/local/etc/php/php.ini
      - /bctos/server/php74/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    cap_add:
      - SYS_PTRACE