version: "3.1"
networks:
  default:
    external:
      name: bctos

services:
  redis50:
    hostname: redis50
    container_name: redis50
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - /bctos/server/redis50/data:/data