version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  mysql57:
    hostname: mysql57
    container_name: mysql57
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/mysql:5.7
    restart: unless-stopped
    ports:
      - 3357:3306
    volumes:
      - /bctos/server/mysql57/mysql-data:/var/lib/mysql
      - /bctos/server/mysql57/my.cnf:/etc/mysql/conf.d/my.cnf
      - /bctos/server/mysql57/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: bctos_panel
      MYSQL_DATABASE: bctos_panel