version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  mysql56:
    hostname: mysql56
    container_name: mysql56
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - 3356:3306
    volumes:
      - /bctos/server/mysql56/mysql-data:/var/lib/mysql
      - /bctos/server/mysql56/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: bctos_panel