version: "3.8"
networks:
  default:
    external:
      name: bctos
services:
  php80:
    build: /bctos/server/php80
    hostname: php80
    container_name: php80
    image: bctos-php:8.0-rc-fpm-alpine
    restart: unless-stopped
    volumes:
      - /bctos/wwwroot:/bctos/wwwroot
      - /bctos/logs:/bctos/logs
      - /bctos/server/php80/php.ini:/usr/local/etc/php/php.ini
      - /bctos/server/php80/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    cap_add:
      - SYS_PTRACE