version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  mysql-mariadb102:
    hostname: mysql-mariadb102
    container_name: mysql-mariadb102
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/mariadb:10.2
    restart: unless-stopped
    ports:
      - 3312:3306
    volumes:
      - /bctos/server/mysql-mariadb102/mysql-data:/var/lib/mysql
      - /bctos/server/mysql-mariadb102/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: bctos_panel