version: "3.1"
networks:
  default:
    external:
      name: bctos
services:
  mysql-mariadb103:
    hostname: mysql-mariadb103
    container_name: mysql-mariadb103
    image: registry.cn-hangzhou.aliyuncs.com/wxm201411/mariadb:10.3
    restart: unless-stopped
    ports:
      - 3313:3306
    volumes:
      - /bctos/server/mysql-mariadb103/mysql-data:/var/lib/mysql
      - /bctos/server/mysql-mariadb103/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: bctos_panel